import { Router } from "express";
import auth from "./auth.js";
import dashboard from "./dashboard.js";
import users from "./users.js";
import farms from "./farms.js";
import crops from "./crops.js";
import listings from "./listings.js";
import orders from "./orders.js";
import marketPrices from "./market-prices.js";
import diseaseReports from "./disease-reports.js";
import weather from "./weather.js";
import notifications from "./notifications.js";
import aiModels from "./ai-models.js";
import subscriptions from "./subscriptions.js";
import payments from "./payments.js";
import cms from "./cms.js";
import support from "./support.js";
import analytics from "./analytics.js";
import reports from "./reports.js";
import security from "./security.js";
import auditLogs from "./audit-logs.js";
import settings from "./settings.js";
import superAdmin from "./super-admin.js";

const router = Router();

router.use("/auth", auth);
router.use("/dashboard", dashboard);
router.use("/users", users);
router.use("/farms", farms);
router.use("/crops", crops);
router.use("/listings", listings);
router.use("/orders", orders);
router.use("/market-prices", marketPrices);
router.use("/disease-reports", diseaseReports);
router.use("/weather", weather);
router.use("/notifications", notifications);
router.use("/ai-models", aiModels);
router.use("/subscriptions", subscriptions);
router.use("/payments", payments);
router.use("/cms", cms);
router.use("/support", support);
router.use("/analytics", analytics);
router.use("/reports", reports);
router.use("/security", security);
router.use("/audit-logs", auditLogs);
router.use("/settings", settings);
router.use("/super-admin", superAdmin);

export default router;
