import { Router } from "express";
import auth from "./auth.routes.js";
import users from "./user.routes.js";
import farms from "./farm.routes.js";
import crops from "./crop.routes.js";
import market from "./market.routes.js";
import orders from "./order.routes.js";
import notifications from "./notification.routes.js";
import weather from "./weather.routes.js";
import dashboard from "./dashboard.routes.js";
import ai from "./ai.routes.js";
import marketPrices from "./marketPriceRoutes.js";
import adminMarketPrices from "./adminMarketPriceRoutes.js";
import admin from "../admin-routes/index.js";

const router = Router();
router.use("/auth", auth);
router.use("/users", users);
router.use("/farms", farms);
router.use("/crops", crops);
router.use("/market", market);
router.use("/orders", orders);
router.use("/notifications", notifications);
router.use("/weather", weather);
router.use("/dashboard", dashboard);
router.use("/ai", ai);
router.use("/market-prices", marketPrices);
router.use("/admin/market-prices", adminMarketPrices);
router.use("/admin", admin);
export default router;
